import './globals.css'
import { Inter } from 'next/font/google'
import mobile from './mobile.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <link href="https://fonts.googleapis.com/css2?family=Pangolin&display=swap" rel="stylesheet"/> 
      </head>
      <body className={[inter.className, mobile.container].join(' ')}>
        <div className={mobile.window}>
          {children}
        </div>
      </body>
    </html>
  )
}
